@startuml
actor Usuario
participant "MainActivity" as Main
participant "AddRecipeActivity" as Add
participant "BaseRecipeActivity" as Base
participant "AppUtils" as Utils
participant "RecipeProvider" as DB
participant "Servidor" as Server
participant "ConnectionWorker" as WM

== Inicio ==
Usuario -> Main : onClick(buttonAdd)
Main -> Add : startActivity(Intent)

activate Add

Usuario -> Add : onClick(buttonSave)

alt userId != -1 (modo online)
    Add -> Add : saveRecipeToServer(userId)
    Add -> Base : uploadImageToServer(imagePath, listener)

    alt si no es la imagen predeterminada (si el usuario ha añadido una)
        Base -> Utils : uploadImageToServer()
        Utils -> Server : POST imagen (multipart)
        Server --> Utils : JSON con ruta en servidor
        Utils --> Base : onSuccess(imagePathOnServer)
        Base --> Add : listener.onImageUploaded(imagePathOnServer)
    else la imagen es la predeterminada (no hay que volver a subirla al servidor)
        Base --> Add : listener.onImageUploaded(imagePathOnServer)
    end

    Add -> WM : enqueue(save_recipe)
    WM -> Server : POST receta (name, image, ingredients, steps, userId)
    Server --> WM : Respuesta JSON (success/mensaje)
    WM --> Add : Resultado
    Add -> Usuario : Toast resultado
    Add -> Main : finish()
else (modo offline)
    Add -> Add : saveRecipe()
    Add -> DB : insert(nombre, imagen, ingredientes, pasos)
    DB --> Add : URI resultado
    Add -> Usuario : Toast resultado
    Add -> Main : finish()
end
deactivate Add
@enduml
